[package]
name = "password-generator-cli"
version = "0.1.0"
authors = ["karmeleonik <szymon.trybala@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.0"
clap = "~2.33.0"